name: $name
version: $version
api-version: "$apiVersion"
main: me.marlester.rfp.ReallyFakePlayers
loader: me.marlester.rfp.ReallyFakePlayersLoader
description: $description
load: POSTWORLD
authors:
  - Marlester
  - freethemice
website: "https://dev.bukkit.org/projects/really-fake-players"
dependencies:
  server:
    MiniPlaceholders:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: false
